### ISSUE TITLE
is deepObject supported yet ?

### ISSUE THREAD

**Issue by bandirsen** [gibahjoe/openapi-generator-dart#11]
I wonder if deepObject already supported by this generator

I'm trying with this spec :
path:
```
/api/v1/users:
    get:
      description: Get User List
      operationId: getUserList
      parameters:
        - in: query
          name: filter
          schema:
            $ref: "#/components/schemas/UserFilter"
          style: deepObject
          explode: true
       - in: query
          name: pagination
          schema:
            $ref: "#/components/schemas/Pagination"
          style: deepObject
          explode: true
```
component:
```
UserFilter:
      type: object
      properties:
        name:
          type: string        
        email:
          type: string

Pagination:
      type: object
      required:
        - limit
        - offset
      properties:
        limit:
          type: integer
          maximum: 20
        offset:
          type: intege
```

the generated client api is like this: 

```
Future<Response<List<User>>> getUserList({
    UserFilter filter,
    Pagination pagination,
    CancelToken cancelToken,
    Map<String, String> headers,
  }) async {
    String _path = "/api/v1/leads";

    Map<String, dynamic> queryParams = {};
    Map<String, String> headerParams = Map.from(headers ?? {});
    dynamic bodyData;

    queryParams[r'filter'] = filter;    <<======  Not serialized, not encoded into deepObject format ??
    queryParams[r'pagination'] = pagination;    <<======  Not serialized, not encoded into deepObject format ??
    queryParams.removeWhere((key, value) => value == null);
    headerParams.removeWhere((key, value) => value == null);

    List<String> contentTypes = [];

    return _dio
        .request(
      _path,
      queryParameters: queryParams,
      data: bodyData,
      options: Options(
        method: 'get'.toUpperCase(),
        headers: headerParams,
        extra: {
          'secure': [
            {"type": "http", "name": "bearerAuth"}
          ],
        },
        contentType:
            contentTypes.isNotEmpty ? contentTypes[0] : "application/json",
      ),
      cancelToken: cancelToken,
    )
.... omitted for clarity
```

As openapi specification 3, the api request should be like this
`http://localhost/api/v1/users?filter[name]=XXX&filter[email]=yyy@yyy.com&pagination[limit]=10&pagination[offset]=0`

but I got this from generator, which is an invalid query URL
`http://localhost/api/v1/users?filter:UserFilter {name=XXX,email=yyy@yyy.com}&pagination: Pagination {limit=10, offset=0}`

Is there some steps I miss ? or deepObject not supported yet by this generator ? 

Thank you.
