### ISSUE TITLE
Generator adds comment into version controlled source file containing the Openapi annotation

### ISSUE THREAD

**Issue by thomasgi1** [gibahjoe/openapi-generator-dart#131]
### Description of the bug

Every time, when the OpenAPI generator runs, it adds following comment line to the source file containing the Openapi annotation:
```
// Openapi Generator last run: : 2024-02-01T14:45:00.661335
```
Since that source file is typically under source control its automatic modification is very annoying, because a developer has either to revert the git change or commit it after each `dart run build_runner build`. The situation becomes even worse, if the `dart run build_runner build` is executed each time before the normal `flutter build`.

### Steps to reproduce

execute `dart run build_runner build`

### Expected behavior

The source file containing the openapi annotation is not touched.

### Platform

macOS

### Library version

5.0.2

### Flutter version

3.16.9

### Flutter channel

stable

**Comment by aoisupersix** [comment]
I have the same issue.
I've submitted a PR (#139) to allow optional updates to the annotated file. 

And also, as a temporary workaround, I've created a script that removes timestamp comment using [rps](https://pub.dev/packages/rps).

pubspec.yaml:

```yaml
scripts:
  gen-apiclient:
    $script: dart run build_runner build --delete-conflicting-outputs --build-filter='lib/my_generator_config.dart'
    $after: $remove-timestamp
  remove-timestamp:
    $script:
      $windows: powershell -Command "(Get-Content lib\my_generator_config.dart) -notmatch '^\/\/ Openapi Generator last run' | Foreach-Object { $_ + \"`n\" } | Set-Content lib\my_generator_config.dart -NoNewline"
      $default: sed -i '' '/^\/\/ Openapi Generator last run/d' lib/my_generator_config.dart
```

**Comment by grAPPfruit** [comment]
If you don't need to rebuild the API everytime the build runner runs, then add this to your `build.yaml`:

```yaml
targets:
  $default:
    builders:
      openapi_generator:
        enabled: false
```

if you add a new spec or need to update, just set `enabled: true`.

Hope this helps!
