### ISSUE TITLE
nullable array fields are not handled properly in the generated `fromJson`

### ISSUE THREAD

**Issue by alexpyc** [gibahjoe/openapi-generator-dart#140]
### Description of the bug

A field is defined as nullable array. Yet it will be generated to have empty List in dart which causes an issue as there is a difference between null and empty List in my case.

### Steps to reproduce

```
SomeObject:
    type: object
    properties:
        category_ids:
            nullable: true
            type: array
            items:
                type: string
```

### Expected behavior

SomeObject currently has the field categoryIds which is nullable List in dart. However it is expected that in fromJson, it can differentiate between `null` and empty array

### Platform

Linux

### Library version

4.13.1

### Flutter version

3.10.6

### Flutter channel

stable
