### ISSUE TITLE
Null field for propertyName when discriminator used in deserializer

### ISSUE THREAD

**Issue by andreykud** [gibahjoe/openapi-generator-dart#167]
### Description of the bug

When discriminator used in api specification it seems common fields for inherited objects not filled in dart generator implementation.

It seems generated dart code does not calls method named '_deserializeProperties' in method 'deserialize' (in test.dart).
So in generated test.g.dart when _build calls it throws an Exception, because type was not parsed and it is null.

Manual adding call this method to generated code fixes issue

### Steps to reproduce

Generate code by specification below

### Minimal openapi specification

test-contract.yml
```yaml
openapi: 3.0.3
info:
  version: '1.0'
  title: Test
paths:
  /test:
    get:
      operationId: test
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: "./test.yml"
```

test.yml:
```yaml
type: object
oneOf:
  - $ref: './a.yml'
  - $ref: './b.yml'
discriminator:
  propertyName: type
required:
  - type
properties:
  type:
    $ref: './testType.yml'
```

testType.yml:
```yaml
type: string
enum:
  - a
  - b
```

a.yml:
```yaml
type: object
properties:
  optionA1:
    type: string
```

b.yml:
```yaml
type: object
properties:
  optionB1:
    type: string
```

### Annotation used

@Openapi(
    additionalProperties: AdditionalProperties(
      pubName: 'test_api',
    ),
    inputSpec: InputSpec(path: '../../../common/contract/test-contract.yml'),
    generatorName: Generator.dio,
    runSourceGenOnOutput: true,
    outputDirectory: '../generated/test_api')

### Expected behavior

Generator should generate without errors

### Platform

Windows

### Library version

6.0.0

### Flutter version

3.24.3

### Flutter channel

stable
