### ISSUE TITLE
Error: Invalid spec file format on Generation.

### ISSUE THREAD

**Issue by GitGud31** [gibahjoe/openapi-generator-dart#171]
### Description of the bug

I cannot generate Dart code for my models and apis with an error in the Invalid spec file format. Please check Logs section.

```
dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.9.0
  openapi_generator_annotations: ^6.1.0
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  openapi_generator: ^6.1.0
```

### Steps to reproduce

Create a Flutter project and add the openapi annotation on any class.

### Minimal openapi specification

Follow doc example.

### Annotation used

```
// Openapi Generator last run: : 2024-12-17T12:11:24.358143
import 'package:openapi_generator_annotations/openapi_generator_annotations.dart';

@Openapi(
  additionalProperties: DioAltProperties(pubName: "dev_file_manager"),
  inputSpec: RemoteSpec(path: <MY REMOTE PATH>),
  generatorName: Generator.dio,
  runSourceGenOnOutput: true,
  outputDirectory: "lib/apis/file_manager",
  forceAlwaysRun: true,
)
class FileManager {}
```

### Expected behavior

Generate dart code as expected.

### Screenshots

![image](https://github.com/user-attachments/assets/959caee3-3c0a-4f2b-92d6-106fac728755)

### Platform

Android

### Library version

6.1.0

### Flutter version

3.24.1

### Flutter channel

stable
