### ISSUE TITLE
Target of URI doesn't exist: 'package:my_api/model/any_type.dart'.

### ISSUE THREAD

**Issue by tiholic** [gibahjoe/openapi-generator-dart#39]
Config:

```dart
import 'package:openapi_generator_annotations/openapi_generator_annotations.dart';

@Openapi(
    additionalProperties: AdditionalProperties(
      pubName: 'my_api',
      pubAuthor: 'XYZ',
    ),
    inputSpecFile: 'assets/schema.yaml',
    generatorName: Generator.DART_DIO,
    outputDirectory: 'api/')
class APIConfig extends OpenapiGeneratorConfig {}
```

With this config, I see the generated package shows this error: 

`Target of URI doesn't exist: 'package:chartered_api/model/any_type.dart'.`

Tried using pure dart (`generatorName: Generator.DART`) that also throws the same error.

Also when DIO is chosen, the created dependencies are outdated.
This is list of dependencies that work with build runner (alongisde flutter 2.0)

```yaml
dependencies:
    dio: ^3.0.9
    built_value: ^8.0.2
    built_collection: ^5.0.0
dev_dependencies:
    built_value_generator: ^8.0.2
    build_runner: ^1.11.5
```
