### ISSUE TITLE
Version 4.0.0 not released

### ISSUE THREAD

**Issue by atoka93** [gibahjoe/openapi-generator-dart#76]
The latest version on `master` for the `openapi-generator` package both in `CHANGELOG.md` and `pubspec.yaml` is `4.0.0` but the released version on [pub.dev](https://pub.dev/packages/openapi_generator) is the previous version `3.3.2`.

**Comment by atoka93** [comment]
A workaround:
```yaml
dependencies:
  openapi_generator_annotations: 
    git:
      url: https://github.com/gibahjoe/openapi-generator-dart.git
      ref: master
      path: openapi-generator-annotations
```
