### ISSUE TITLE
Deserialize Enum throw Error on response that was changed (added more Enum value)

### ISSUE THREAD

**Issue by NguyenVanCong1902** [gibahjoe/openapi-generator-dart#77]
Hi, I'm using openapi-generator v4.0.0

I generated Classes with api-docs-file.yaml that contains these lines:
```
properties:
  testEnum:
    type: string
    description: testing enum value added
    enum:
      - TEST1
      - TEST2
      - TEST3
```

It work well if backend response data like:
`
{
    testEnum: 'TEST1'
}
`

But after backend adding new value to Enum (example TEST4), then response data like:
`
{
    testEnum: 'TEST4'
}
`

then below code (generated by openapi-generator v4.0.0) will throw Error because it can't parse 'TEST4' to testEnum

```
    TestResponse _responseData;

    try {
      const _responseType = FullType(TestResponse);
      _responseData = _serializers.deserialize(
        _response.data!,
        specifiedType: _responseType,
      ) as TestResponse ;

    } catch (error, stackTrace) {
      throw DioError(
        requestOptions: _response.requestOptions,
        response: _response,
        type: DioErrorType.other,
        error: error,
      )..stackTrace = stackTrace;
    }
```

How to avoid this error by someway? Is there anyway to access TestResponse.testEnum as String instead of Class?
