### ISSUE TITLE
Dio generator not correctly processing v3.1.0 spec (converts String to JsonObject)

### ISSUE THREAD

**Issue by Nexushunter** [gibahjoe/openapi-generator-dart#94]
### Description of the bug

When using this config:
```dart
const _apiLink = 'https://api.tagmine.ca/openapi.yaml';

@Openapi(
  additionalProperties: DioProperties(
    pubName: 'tagmine_api',
    pubDescription: 'OAS generated dart api for tagmine.ca',
    useEnumExtension: true,
    sortParamsByRequiredFlag: true,
    sortModelPropertiesByRequiredFlag: true,
    nullableFields: false
  ),
  inputSpecFile: _apiLink,
  generatorName: Generator.dio,
  outputDirectory: 'clients/dart',
  overwriteExistingFiles: false,
  alwaysRun: true,
  fetchDependencies: true,
  // Try to add missing import???
  importMappings: {
    'JsonObject': 'package:built_value/json_object.dart',
  },
)
class TagmineClientConfig extends OpenapiGeneratorConfig {}
```

The resulting library produces incorrect artifacts. All of the `src/api/*_api.dart` files are missing the `JsonObject` import which is imported from `package:built_value/json_object.dart`

### Steps to reproduce

Run `dart run build_runner build --delete-conflicting-outputs` with this in the `build.yml`

```yaml
builders:
  openapi_generator:
    target: ":openapi_generator"
    import: "package:openapi_generator/src/builder.dart"
    builder_factories: [ "openApiClientSdk" ]
    build_extensions: { ".dart": [ ".g.part" ] }
    auto_apply: dependents
    build_to: cache
    applies_builders: [ "source_gen|combining_builder" ]

targets:
  $default:
    builders:
      openapi_generator:openapi_generator_annotations:
        generate_for:
          - lib/client_generator_config.dart
```

and the contents of the config within `lib/client_generator_config.dart`

### Expected behavior

No missing imports in generated code.

### Platform

Linux

### Library version

4.11.0

### Flutter version

3.0.5 - Dart

### Flutter channel

stable

### Additional context

```text
This is done purely in dart project.
```
